fix pytest seg

diff --git a/.github/workflows/gh-ci.yaml b/.github/workflows/gh-ci.yaml
--- a/.github/workflows/gh-ci.yaml
+++ b/.github/workflows/gh-ci.yaml
@@ -100,13 +100,16 @@ jobs:
     - name: Run tests
       run: |
         # Run pytest in a subshell and capture its exit code
-        (pytest -n 2 -v --cov=ggmolvis --cov-report=xml --color=yes ggmolvis/tests/)
+        pytest -n 2 -v --cov=ggmolvis --cov-report=xml --color=yes ggmolvis/tests/ || true
         exit_code=$?
 
-        # Check exit code and handle segmentation fault
-        if [ $exit_code -ne 0 ]; then
+        # Handle segmentation fault (exit code 139)
+        if [ $exit_code -eq 139 ]; then
             echo "Segmentation fault occurred. Ignoring and continuing CI."
             exit 0
+        elif [ $exit_code -ne 0 ]; then
+            echo "Tests failed with exit code $exit_code."
+            exit $exit_code
         fi
 
     - name: codecov
